### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Arpit-Satpute** [xoureldeen/Vectras-VM-Android#45]
Time Of Crash :    2024_04_20-16_11_07
Device :    motorola, motorola edge 30
Android Version :    13 (33)
App Version :    v2.8-debug-build-5 (15)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a, armeabi-v7a, armeabi]
Fingerprint :    motorola/dubai_g/dubai:13/T1RDS33.116-33-13-3/2256b-8a4321:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Process.waitFor()' on a null object reference
	at com.vectras.vterm.Terminal.lambda$executeShellCommand$0$com-vectras-vterm-Terminal(Terminal.java:145)
	at com.vectras.vterm.Terminal$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by epicstudios856** [comment]
@Arpit-Satpute Thank u for bug report, i will look about this

**Comment by Rkpain** [comment]
Time Of Crash :    2024_04_26-02_18_53
Device :    samsung, SM-A346E
Android Version :    14 (34)
App Version :    v2.8-debug-build-5 (15)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a, armeabi-v7a, armeabi]
Fingerprint :    samsung/a34xdxx/a34x:14/UP1A.231005.007/A346EXXS6BXD7:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.androidVNC.RfbProto.writeKeyEvent(int, int, boolean)' on a null object reference
	at android.androidVNC.VncCanvas.sendMetaKey1(VncCanvas.java:1203)
	at com.vectras.qemu.MainVNCActivity$42.run(MainVNCActivity.java:1144)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by epicstudios856** [comment]
@Rkpain show me the logs from the app logger

**Comment by contactsikandar** [comment]
Time Of Crash :    2024_05_09-12_15_10
Device :    INFINIX, Infinix X6833B
Android Version :    13 (33)
App Version :    2.2 (6)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a, armeabi-v7a, armeabi]
Fingerprint :    Infinix/X6833B-GL/Infinix-X6833B:13/TP1A.220624.014/240220V3535:user/release-keys

android.util.AndroidRuntimeException: Animators may only be run on Looper threads
	at android.animation.ValueAnimator.cancel(ValueAnimator.java:1195)
	at android.graphics.drawable.RippleDrawable.exitPatternedBackgroundAnimation(RippleDrawable.java:827)
	at android.graphics.drawable.RippleDrawable.setBackgroundActive(RippleDrawable.java:376)
	at android.graphics.drawable.RippleDrawable.onStateChange(RippleDrawable.java:337)
	at android.graphics.drawable.Drawable.setState(Drawable.java:836)
	at android.view.View.drawableStateChanged(View.java:24311)
	at android.widget.TextView.drawableStateChanged(TextView.java:6151)
	at android.widget.CompoundButton.drawableStateChanged(CompoundButton.java:586)
	at androidx.appcompat.widget.AppCompatCheckBox.drawableStateChanged(AppCompatCheckBox.java:251)
	at android.view.View.refreshDrawableState(View.java:24393)
	at android.view.View.setEnabled(View.java:12373)
	at android.widget.TextView.setEnabled(TextView.java:2357)
	at com.google.android.material.checkbox.MaterialCheckBox.setEnabled(MaterialCheckBox.java:347)
	at com.vectras.vm.RomsManagerActivity$2.run(RomsManagerActivity.java:191)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by xoureldeen** [comment]
fixed
